const himymEpisodes = [
    // Season 1
    { season: 1, episode: 1, title: "Pilot", description: "Ted tells his kids the story of how he met their mother.", imdbRating: 8.4 },
    { season: 1, episode: 2, title: "Purple Giraffe", description: "Ted throws multiple parties to impress Robin.", imdbRating: 8.0 },
    { season: 1, episode: 3, title: "The Sweet Taste of Liberty", description: "Barney's plan to meet girls at the airport backfires.", imdbRating: 8.0 },
    { season: 1, episode: 4, title: "Return of the Shirt", description: "Ted reconnects with an old flame and remembers why he dumped her.", imdbRating: 7.8 },
    { season: 1, episode: 5, title: "Okay Awesome", description: "Robin, Ted, and Barney go to a hot new club, leaving Marshall and Lily to a boring evening of wine tasting.", imdbRating: 8.1 },
    { season: 1, episode: 6, title: "The Slutty Pumpkin", description: "Ted hopes to reunite with a girl he met at a Halloween party years ago.", imdbRating: 7.9 },
    { season: 1, episode: 7, title: "Matchmaker", description: "Ted signs up with a matchmaking service and learns that love is not a science.", imdbRating: 7.5 },
    { season: 1, episode: 8, title: "The Duel", description: "Ted and Marshall duel over the apartment when Lily moves in.", imdbRating: 8.0 },
    { season: 1, episode: 9, title: "Belly Full of Turkey", description: "Lily and Marshall visit his family for Thanksgiving, while Robin and Ted volunteer at a shelter.", imdbRating: 7.9 },
    { season: 1, episode: 10, title: "The Pineapple Incident", description: "After a drunken night, Ted awakens to find a woman and a pineapple in his bed.", imdbRating: 9.1 },
    { season: 1, episode: 11, title: "The Limo", description: "Ted rents a limo to give his friends a great New Year's Eve.", imdbRating: 8.2 },
    { season: 1, episode: 12, title: "The Wedding", description: "Ted invites Robin to a wedding, only to discover he doesn't have a plus one.", imdbRating: 8.0 },
    { season: 1, episode: 13, title: "Drumroll, Please", description: "Ted meets a mysterious woman at a wedding and searches for her afterward.", imdbRating: 8.7 },
    { season: 1, episode: 14, title: "Zip, Zip, Zip", description: "Barney and Robin enjoy a night of cigars and laser tag, while Ted and Victoria face relationship milestones.", imdbRating: 8.1 },
    { season: 1, episode: 15, title: "Game Night", description: "Marshall's game night leads to some startling and embarrassing revelations.", imdbRating: 9.0 },
    { season: 1, episode: 16, title: "Cupcake", description: "Ted and Victoria face challenges when she gets an opportunity in Germany.", imdbRating: 7.7 },
    { season: 1, episode: 17, title: "Life Among the Gorillas", description: "Marshall struggles to fit in at Barney's workplace.", imdbRating: 7.5 },
    { season: 1, episode: 18, title: "Nothing Good Happens After 2 AM", description: "Ted makes questionable decisions when he visits Robin late at night.", imdbRating: 8.3 },
    { season: 1, episode: 19, title: "Mary the Paralegal", description: "Ted needs a date for an event and considers going with a mysterious woman.", imdbRating: 8.7 },
    { season: 1, episode: 20, title: "Best Prom Ever", description: "Lily crashes a high school prom to hear a potential wedding band.", imdbRating: 7.7 },
    { season: 1, episode: 21, title: "Milk", description: "Ted is set up with his 'perfect' match but is distracted by feelings for Robin.", imdbRating: 8.0 },
    { season: 1, episode: 22, title: "Come On", description: "Ted makes a grand gesture to win Robin, while Marshall and Lily face challenges.", imdbRating: 8.5 },

    // Season 2
    { season: 2, episode: 1, title: "Where Were We?", description: "The gang tries to help Marshall get over his breakup with Lily.", imdbRating: 8.3 },
    { season: 2, episode: 2, title: "The Scorpion and the Toad", description: "Barney helps Marshall get back into the dating scene.", imdbRating: 8.0 },
    { season: 2, episode: 3, title: "Brunch", description: "The gang's brunch with Ted's parents leads to surprising revelations.", imdbRating: 8.3 },
    { season: 2, episode: 4, title: "Ted Mosby: Architect", description: "Robin questions Ted's career, leading him to prove architects can be sexy.", imdbRating: 8.4 },
    { season: 2, episode: 5, title: "World's Greatest Couple", description: "Barney and Lily become roommates, leading to unexpected situations.", imdbRating: 8.3 },
    { season: 2, episode: 6, title: "Aldrin Justice", description: "Lily takes a job as an office assistant and teaches her boss a lesson.", imdbRating: 8.1 },
    { season: 2, episode: 7, title: "Swarley", description: "Marshall starts dating a new girl, leading to concerns from the gang.", imdbRating: 9.0 },
    { season: 2, episode: 8, title: "Atlantic City", description: "Marshall and Lily elope to Atlantic City but face unexpected obstacles.", imdbRating: 8.3 },
    { season: 2, episode: 9, title: "Slap Bet", description: "The gang learns about Robin's past as a Canadian pop star.", imdbRating: 9.5 },
    { season: 2, episode: 10, title: "Single Stamina", description: "Barney's brother visits, revealing surprising news.", imdbRating: 8.2 },
    { season: 2, episode: 11, title: "How Lily Stole Christmas", description: "Lily and Ted have a falling out during the holiday season.", imdbRating: 8.3 },
    { season: 2, episode: 17, title: "Arrivederci, Fiero", "description": "Marshall's beloved car, the Fiero, breaks down, prompting the gang to reminisce about their memorable experiences with the vehicle.", imdbRating: 8.4 },
    { season: 2, episode: 19, title: "Bachelor Party", "description": "Barney's misguided attempts to throw Marshall a memorable bachelor party lead to unexpected revelations and chaos.", imdbRating: 8.3 },
    { season: 2, episode: 20, title: "Showdown", "description": "Barney appears on 'The Price Is Right,' believing that Bob Barker is his father, while Marshall and Lily finalize their wedding plans.", imdbRating: 8.4 },
    { season: 2, episode: 21, title: "Something Borrowed", "description": "Marshall and Lily's wedding day faces a series of comedic disasters, leading them to rethink their big ceremony plans.", imdbRating: 8.7 },
    { season: 3, episode: 5, title: "How I Met Everyone Else", "description": "Ted's new girlfriend prompts the gang to share the humorous and exaggerated stories of how they all met.", imdbRating: 8.9 },
    { season: 3, episode: 8, title: "Spoiler Alert", "description": "Ted's infatuation with his new girlfriend blinds him to her annoying habit, leading the gang to point out each other's flaws.", imdbRating: 8.5 },
    { season: 3, episode: 9, title: "Slapsgiving", "description": "The gang's Thanksgiving is overshadowed by the impending third slap in Marshall and Barney's slap bet.", imdbRating: 9.0 },
    { season: 3, episode: 11, title: "The Platinum Rule", "description": "The gang warns Ted about the dangers of dating someone you see regularly, sharing their own cautionary tales.", imdbRating: 8.4 },
    { season: 3, episode: 12, title: "No Tomorrow", "description": "Ted joins Barney for a wild St. Patrick's Day party, leading to questionable decisions and reflections on karma.", imdbRating: 8.2 },
    { season: 3, episode: 13, title: "Ten Sessions", "description": "Ted's romantic pursuit of his dermatologist, Stella, leads to a memorable two-minute date.", imdbRating: 8.8 },
    { season: 3, episode: 14, title: "The Bracket", "description": "Barney creates a tournament bracket to identify which of his past conquests is sabotaging his future prospects.", imdbRating: 8.4 },
    { season: 3, episode: 16, title: "Sandcastles in the Sand", "description": "Robin rekindles a romance with an old flame, leading to the unveiling of another Robin Sparkles music video.", imdbRating: 8.4 },
    { season: 4, episode: 2, title: "The Best Burger in New York", "description": "Marshall takes the gang on a quest to find a burger he had during his first week in New York City.", imdbRating: 8.5 },
    { season: 4, episode: 7, title: "Not a Father's Day", "description": "Barney creates a holiday for men who are not fathers after a pregnancy scare.", imdbRating: 7.9 },
    { season: 4, episode: 9, title: "The Naked Man", "description": "The gang learns about a move called 'The Naked Man' that works to get dates into bed.", imdbRating: 9.0 },
    { season: 4, episode: 12, title: "Benefits", "description": "Ted and Robin become 'friends with benefits' to avoid arguments, complicating their friendship.", imdbRating: 8.6 },
    { season: 4, episode: 14, title: "The Possimpible", "description": "Robin needs to find a job in seven days or be deported; Barney helps her create a video resume.", imdbRating: 8.4 },
    { season: 4, episode: 15, title: "The Stinsons", "description": "The gang discovers that Barney has been keeping a secret family.", imdbRating: 8.2 },
    { season: 4, episode: 17, title: "The Front Porch", "description": "Ted learns that Lily has been sabotaging his relationships to keep the group together.", imdbRating: 8.4 },
    { season: 4, episode: 19, title: "Murtaugh", "description": "Ted and Barney challenge each other to complete a list of things they're too old and too young to do.", imdbRating: 8.5 },
    { season: 4, episode: 20, title: "Mosbius Designs", "description": "Ted starts his own architecture firm; Barney tries to sleep with Ted's new assistant.", imdbRating: 7.8 },
    { season: 4, episode: 22, title: "Right Place Right Time", "description": "Ted encounters someone from his past at the right place and time, leading to a significant opportunity.", imdbRating: 8.0 },
    { season: 4, episode: 23, title: "As Fast as She Can", "description": "Ted tries to help Stella's fiancé find a job; Barney tries to talk his way out of a speeding ticket.", imdbRating: 7.9 },
    { season: 4, episode: 24, title: "The Leap", "description": "Ted considers a big change in his career; Marshall builds up the courage to jump from the rooftop to the adjacent building.", imdbRating: 8.8 },
    // Season 5 Episodes
    { season: 5, episode: 1, title: "Definitions", description: "Lily forces Barney and Robin to define their relationship; Ted begins his new job as a professor.", imdbRating: 8.5 },
{ season: 5, episode: 4, title: "The Sexless Innkeeper", description: "Marshall and Lily try to find a couple to double date with; Barney creates a video to impress women.", imdbRating: 7.8 },
{ season: 5, episode: 6, title: "Bagpipes", description: "Marshall and Lily's relationship is tested when Barney and Robin have a fight.", imdbRating: 7.9 },
{ season: 5, episode: 8, title: "The Playbook", description: "After breaking up with Robin, Barney dusts off his 'playbook' to help him get back into the dating scene.", imdbRating: 9.2 },
{ season: 5, episode: 10, title: "The Window", description: "Ted pursues a woman who is finally single; Marshall struggles with writing a letter to his future child.", imdbRating: 8.1 },
{ season: 5, episode: 12, title: "Girls vs. Suits", description: "Barney debates giving up wearing suits to land a hot bartender; Ted gets closer to meeting the mother.", imdbRating: 9.0 },
{ season: 5, episode: 14, title: "Perfect Week", description: "Barney attempts to have a 'perfect week' by hooking up with seven different women in seven days.", imdbRating: 8.9 },
{ season: 5, episode: 17, title: "Of Course", description: "Robin sets Barney up with a self-help author to get back at him for the way he handled their breakup.", imdbRating: 8.3 },
{ season: 5, episode: 24, title: "Doppelgangers", description: "The gang searches for their doppelgangers; Marshall and Lily decide to start trying for a baby.", imdbRating: 8.5 },
{ season: 6, episode: 4, title: "Subway Wars", description: "The gang competes to determine the quickest way to reach a downtown restaurant, showcasing their competitive sides.", imdbRating: 8.3 },
{ season: 6, episode: 9, title: "Glitter", description: "Robin's past as a Canadian pop star resurfaces when the gang discovers an old music video featuring her and her former best friend.", imdbRating: 8.1 },
{ season: 6, episode: 10, title: "Blitzgiving", description: "Ted misses an epic night out, falling victim to 'The Blitz' curse, leading to a Thanksgiving filled with unexpected events.", imdbRating: 8.5 },
{ season: 6, episode: 13, title: "Bad News", description: "Marshall and Lily receive unexpected news about their ability to conceive, leading to a series of emotional events.", imdbRating: 9.5 },
{ season: 6, episode: 14, title: "Last Words", description: "The gang supports Marshall as he deals with the aftermath of his father's passing, leading to heartfelt and humorous moments.", imdbRating: 9.0 },
{ season: 6, episode: 18, title: "A Change of Heart", description: "Barney begins to develop genuine feelings for Nora, causing him to question his playboy lifestyle.", imdbRating: 8.0 },
{ season: 6, episode: 19, title: "Legendaddy", description: "Barney meets his father and is shocked by the differences in their lives. The rest of the gang learn their 'gaps'; knowledge they should have by now, but don't.", imdbRating: 8.1 },
{ season: 6, episode: 21, title: "Hopeless", description: "Barney tries to bond with his father by making his life seem more exciting, leading to a night of exaggerated stories and antics.", imdbRating: 8.0 },
{ season: 6, episode: 24, title: "Challenge Accepted", description: "Ted and Barney embark on a mission to prevent Ted from rekindling a relationship, while Marshall anxiously awaits the outcome of a job interview.", imdbRating: 8.4 },
    // Season 7 Episodes
        { season: 7, episode: 3, title: "Ducky Tie", description: "Barney makes a bet with Marshall that could have him wearing a ridiculous tie for a year, leading to a night of challenges and surprises.", imdbRating: 8.7 },
        { season: 7, episode: 6, title: "Mystery vs. History", description: "The gang debates the merits of learning everything about a person online before a date versus maintaining an air of mystery.", imdbRating: 8.0 },
        { season: 7, episode: 9, title: "Disaster Averted", description: "The gang reminisces about their experiences during Hurricane Irene, revealing secrets and humorous anecdotes.", imdbRating: 8.6 },
        { season: 7, episode: 11, title: "The Rebound Girl", description: "Barney and Ted consider adopting a baby together after a night of reflection on their lives and relationships.", imdbRating: 7.9 },
        { season: 7, episode: 12, title: "Symphony of Illumination", description: "Robin receives unexpected news that leads her to reflect on her life choices, while Marshall decorates the house with Christmas lights.", imdbRating: 9.0 },
        { season: 7, episode: 17, title: "No Pressure", description: "Ted confesses his feelings to Robin, leading to a series of events that test their friendship and future.", imdbRating: 8.4 },
        { season: 7, episode: 19, title: "The Broath", description: "Barney makes Ted swear 'The Broath' to keep a secret about his new relationship, leading to a series of comedic events.", imdbRating: 8.3 },
        { season: 7, episode: 20, title: "Trilogy Time", description: "The gang's tradition of watching the 'Star Wars' trilogy every three years leads them to reflect on their past and future aspirations.", imdbRating: 8.6 },
        { season: 7, episode: 22, title: "Good Crazy", description: "Ted attempts to move on from Robin by going on a series of blind dates, while Marshall prepares for fatherhood.", imdbRating: 7.8 },
        { season: 7, episode: 23, title: "The Magician's Code: Part 1", description: "As Lily goes into labor, the gang reminisces about past events to distract her from the pain.", imdbRating: 8.5 },
        { season: 7, episode: 24, title: "The Magician's Code: Part 2", description: "The gang experiences significant life changes, including births and engagements, leading to new beginnings.", imdbRating: 8.6 },
        { season: 8, episode: 1, title: "Farhampton", description: "Ted reminisces about the time he insisted on leaving Victoria's jilted fiancé a note before they drove off into the sunset together.", imdbRating: 7.9 },
        { season: 8, episode: 2, title: "The Pre-Nup", description: "Barney creates an extensive pre-nuptial agreement that leads the gang to think about their own relationships.", imdbRating: 7.6 },
        { season: 8, episode: 3, title: "Nannies", description: "Marshall and Lily's quest to find a nanny for baby Marvin leads to an unexpected outcome.", imdbRating: 7.5 },
        { season: 8, episode: 4, title: "Who Wants to Be a Godparent?", description: "Marshall and Lily test their friends to determine who would make the best godparents.", imdbRating: 7.7 },
        { season: 8, episode: 5, title: "The Autumn of Break-Ups", description: "As the season of break-ups continues, Ted and Victoria must choose the next step in their relationship.", imdbRating: 7.3 },
        { season: 8, episode: 6, title: "Splitsville", description: "Robin struggles to break up with her boyfriend Nick, while Barney tries to help her out.", imdbRating: 7.8 },
        { season: 8, episode: 7, title: "The Stamp Tramp", description: "Marshall recommends his old law school classmate for a job, but his past recommendations have been less than stellar.", imdbRating: 7.4 },
        { season: 8, episode: 8, title: "Twelve Horny Women", description: "Marshall faces the toughest case of his career against his old friend Brad, leading to a heated courtroom battle.", imdbRating: 7.6 },
        { season: 8, episode: 12, title: "The Final Page: Part Two", description: "Barney's elaborate plan to propose to Robin unfolds, revealing his true feelings.", imdbRating: 9.0 },
        { season: 8, episode: 14, title: "Ring Up!", description: "Ted begins dating a much younger woman and discovers she has a surprising connection to someone in his group.", imdbRating: 7.4 },
        { season: 8, episode: 15, title: "P.S. I Love You", description: "Robin's past as Canadian pop star Robin Sparkles is revisited, revealing a darker side to her music career.", imdbRating: 8.0 },
        { season: 8, episode: 16, title: "Bad Crazy", description: "Ted's attempts to break up with his crazy girlfriend Jeanette don't go as planned.", imdbRating: 7.5 },
        { season: 8, episode: 17, title: "The Ashtray", description: "The gang receives a call from The Captain, leading them to recall their last awkward encounter with him.", imdbRating: 7.7 },
        { season: 8, episode: 18, title: "Weekend at Barney's", description: "Ted and Jeanette break up, leading Barney to use 'The Playbook' to help Ted find a new girlfriend.", imdbRating: 7.8 },
        { season: 8, episode: 19, title: "The Fortress", description: "Robin wants Barney to sell his apartment, but potential buyers are turned off by its bachelor pad characteristics.", imdbRating: 7.5 },
        { season: 8, episode: 21, title: "Romeward Bound", description: "Lily is offered an opportunity to move to Rome for a year, causing her to question her career path.", imdbRating: 7.6 },
        { season: 8, episode: 22, title: "The Bro Mitzvah", description: "Barney's friends throw him a disastrous bachelor party, leading him to question their friendship.", imdbRating: 8.4 },
        { season: 8, episode: 23, title: "Something Old", description: "Robin digs up a locket she buried in Central Park years earlier, hoping to use it in her wedding.", imdbRating: 7.9 },
        { season: 8, episode: 24, title: "Something New", description: "As the gang prepares to go to Robin and Barney's wedding, Ted plans a life-changing move to Chicago.", imdbRating: 8.5 },
        // Season 9 Episodes
    { season: 9, episode: 5, title: "The Poker Game", description: "Barney's loyalty is tested between Robin and his family during a poker game, leading to humorous confrontations.", imdbRating: 7.5 },
{ season: 9, episode: 6, title: "Knight Vision", description: "Ted is faced with choosing between three potential dates for the wedding weekend, each choice leading to different outcomes.", imdbRating: 7.6 },
{ season: 9, episode: 7, title: "No Questions Asked", description: "Marshall enlists the gang's help to delete a text message he sent to Lily, leading to a series of comedic situations.", imdbRating: 7.8 },
{ season: 9, episode: 8, title: "The Lighthouse", description: "Barney is caught between Robin and his mother during a conflict, while Ted and Cassie visit a lighthouse.", imdbRating: 7.6 },
{ season: 9, episode: 9, title: "Platonish", description: "The gang recalls events leading up to Barney's proposal to Robin, exploring themes of destiny and choice.", imdbRating: 8.1 },
{ season: 9, episode: 15, title: "Unpause", description: "The gang attempts to get Barney to reveal secrets while he's intoxicated, leading to unexpected revelations.", imdbRating: 8.5 },
{ season: 9, episode: 16, title: "How Your Mother Met Me", description: "The Mother's perspective is showcased, detailing her journey leading up to meeting Ted.", imdbRating: 9.5 },
{ season: 9, episode: 17, title: "Sunrise", description: "Ted and Robin reflect on their past relationships during a sunrise, leading to moments of closure.", imdbRating: 8.2 },
{ season: 9, episode: 19, title: "Vesuvius", description: "Ted and the Mother share stories at the Farhampton Inn, leading to emotional revelations about their future.", imdbRating: 8.0 },
{ season: 9, episode: 22, title: "The End of the Aisle", description: "Barney and Robin experience last-minute jitters before their wedding, while Ted comes to terms with his feelings.", imdbRating: 8.4 },
{ season: 9, episode: 23, title: "Last Forever: Part One", description: "The gang's lives are explored over the years, showcasing the evolution of their relationships and careers.", imdbRating: 7.7 },
{ season: 9, episode: 24, title: "Last Forever: Part Two", description: "Ted concludes the story of how he met the Mother, leading to a poignant and heartfelt series finale.", imdbRating: 7.5 },
];
 

export default himymEpisodes;
